version: '3'
services:
  banco-do-brasil-firefox:
    container_name: banco-do-brasil-firefox
    image: matsya/banco-do-brasil-firefox
    build: .
    devices:
      - /dev/snd:/dev/snd
    environment:
      - LANG=pt_BR.UTF-8
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/home/ff/.Xauthority
      - HOST_HOSTNAME=${HOSTNAME}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro
      - ~/BankFiles:/home/ff/Downloads
      - /etc/machine-id:/etc/machine-id:ro
